__author__ = 'sweemeng'
from popit.views.persons import PersonDetail
from popit.views.persons import PersonList
from popit.views.persons import PersonContactDetailDetail
from popit.views.persons import PersonContactDetailList
from popit.views.persons import PersonContactDetailLinkDetail
from popit.views.persons import PersonContactDetailLinkList
from popit.views.persons import PersonIdentifierDetail
from popit.views.persons import PersonIdentifierList
from popit.views.persons import PersonIdentifierLinkDetail
from popit.views.persons import PersonIdentifierLinkList
from popit.views.persons import PersonOtherNameDetail
from popit.views.persons import PersonOtherNameList
from popit.views.persons import PersonOtherNameLinkDetail
from popit.views.persons import PersonOtherNameLinkList
from popit.views.persons import PersonLinkDetail
from popit.views.persons import PersonLinkList
from popit.views.organizations import OrganizationDetail
from popit.views.organizations import OrganizationList
from popit.views.organizations import OrganizationContactDetailDetail
from popit.views.organizations import OrganizationContactDetailList
from popit.views.organizations import OrganizationContactDetailLinkDetail
from popit.views.organizations import OrganizationContactDetailLinkList
from popit.views.organizations import OrganizationIdentifierDetail
from popit.views.organizations import OrganizationIdentifierList
from popit.views.organizations import OrganizationIdentifierLinkDetail
from popit.views.organizations import OrganizationIdentifierLinkList
from popit.views.organizations import OrganizationOtherNameDetail
from popit.views.organizations import OrganizationOtherNameList
from popit.views.organizations import OrganizationOtherNameLinkDetail
from popit.views.organizations import OrganizationOtherNameLinkList
from popit.views.organizations import OrganizationLinkDetail
from popit.views.organizations import OrganizationLinkList
from popit.views.misc import AreaDetail
from popit.views.misc import AreaList
from popit.views.misc import AreaLinkDetail
from popit.views.misc import AreaLinkList
from popit.views.post import PostDetail
from popit.views.post import PostList
from popit.views.post import PostContactDetailDetail
from popit.views.post import PostContactDetailList
from popit.views.post import PostContactDetailLinkDetail
from popit.views.post import PostContactDetailLinkList
from popit.views.post import PostOtherLabelsDetail
from popit.views.post import PostOtherLabelsList
from popit.views.post import PostOtherLabelsLinkDetail
from popit.views.post import PostOtherLabelsLinkList
from popit.views.post import PostLinkDetail
from popit.views.post import PostLinkList