# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popit', '0046_auto_20151204_0306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areatranslation',
            options={'default_permissions': (), 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='contactdetailtranslation',
            options={'default_permissions': (), 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='contacttranslation',
            options={'default_permissions': (), 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='identifiertranslation',
            options={'default_permissions': (), 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='linktranslation',
            options={'default_permissions': (), 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='membershiptranslation',
            options={'default_permissions': (), 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='organizationtranslation',
            options={'default_permissions': (), 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='othernametranslation',
            options={'default_permissions': (), 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='persontranslation',
            options={'default_permissions': (), 'managed': True},
        ),
        migrations.AlterModelOptions(
            name='posttranslation',
            options={'default_permissions': (), 'managed': True},
        ),
    ]
