# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popit', '0049_auto_20151218_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='popit.Organization'),
        ),
    ]
