# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popit', '0051_auto_20160113_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='popit.Organization'),
        ),
    ]
