# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-14 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popit', '0054_auto_20170307_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontranslation',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='biography'),
        ),
    ]
