# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-15 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popit', '0055_auto_20170307_0451'),
        ('popit', '0055_auto_20170314_0625'),
    ]

    operations = [
    ]
