# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-19 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popit', '0058_auto_20170418_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='popit.Post', verbose_name='post'),
        ),
        migrations.AddField(
            model_name='relationtranslation',
            name='classification',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='classification'),
        ),
    ]
