# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-23 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popit', '0059_auto_20170419_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtranslation',
            name='subclassification',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subclassification'),
        ),
    ]
